// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/libsv/go-p4"
	"sync"
)

// Ensure, that MerchantReaderMock does implement p4.MerchantReader.
// If this is not the case, regenerate this file with moq.
var _ p4.MerchantReader = &MerchantReaderMock{}

// MerchantReaderMock is a mock implementation of p4.MerchantReader.
//
// 	func TestSomethingThatUsesMerchantReader(t *testing.T) {
//
// 		// make and configure a mocked p4.MerchantReader
// 		mockedMerchantReader := &MerchantReaderMock{
// 			MerchantFunc: func(ctx context.Context) (*p4.Merchant, error) {
// 				panic("mock out the Merchant method")
// 			},
// 		}
//
// 		// use mockedMerchantReader in code that requires p4.MerchantReader
// 		// and then make assertions.
//
// 	}
type MerchantReaderMock struct {
	// MerchantFunc mocks the Merchant method.
	MerchantFunc func(ctx context.Context) (*p4.Merchant, error)

	// calls tracks calls to the methods.
	calls struct {
		// Merchant holds details about calls to the Merchant method.
		Merchant []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockMerchant sync.RWMutex
}

// Merchant calls MerchantFunc.
func (mock *MerchantReaderMock) Merchant(ctx context.Context) (*p4.Merchant, error) {
	if mock.MerchantFunc == nil {
		panic("MerchantReaderMock.MerchantFunc: method is nil but MerchantReader.Merchant was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMerchant.Lock()
	mock.calls.Merchant = append(mock.calls.Merchant, callInfo)
	mock.lockMerchant.Unlock()
	return mock.MerchantFunc(ctx)
}

// MerchantCalls gets all the calls that were made to Merchant.
// Check the length with:
//     len(mockedMerchantReader.MerchantCalls())
func (mock *MerchantReaderMock) MerchantCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMerchant.RLock()
	calls = mock.calls.Merchant
	mock.lockMerchant.RUnlock()
	return calls
}
